### ISSUE TITLE
CKPX doesn't work on some webpages

### ISSUE THREAD

**Issue by sparky-vision** [subdavis/Tusk#33] opened 2017-11-18 01:43 UTC
Occasionally, CKPX will simply fail to work. CKPX seems to enter the information, then gets instantly erased. Netflix demonstrates this problem, as does the New York Times login page.

This might be the intended behavior of the webpage, but it forces the user to manually type or copy / paste the username / password.

**Comment by subdavis** [comment] 2017-11-18 15:54
Hey there, @sparky-vision.

Thanks for the bug report.  I really rely on reports like this to get feedback when things aren't working.

I was able to reproduce the issue on the new york times, and it definitely looks like NYT is actively blocking attempts to autofill the password.  Whether this can be circumvented or not is not yet clear to me - I have some thoughts, but I'll have to play with it.

I was unable to reproduce your issue with Netflix - I use CKPX with netflix often.  I was on https://www.netflix.com/login.  

I'll give this a look, but it may take some time.

**Comment by sparky-vision** [comment] 2017-11-20 18:38
Strange! I may have been having the problem with the CKP and, as I recently upgraded to CKPX, didn't realize the issue with Netflix didn't exist anymore. So yeah, Netflix is good.

**Comment by subdavis** [comment] 2018-07-23 13:06
Duplicate of #197 since I think there's better documentation of the issue there.

**Closed by subdavis** 2018-07-23 13:06 UTC
Labels: bug, help wanted
