### ISSUE TITLE
UUID references are not resolved

### ISSUE THREAD

**Issue by karottenbaum** [subdavis/Tusk#213] opened 2018-08-08 08:19 UTC
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Tusk does not resolve UUID field references (like `{REF:U@I:49e530bd456571c6f6250c0010c22416}`).
This is not good because UUID references are the only way to uniquely identify a stored account, as titles can appear multiple times.

### Please describe how you think it should change.

Please make Tusk resolve UUID references so that multiple domains can point to an exactly identifiable password record.

**Comment by subdavis** [comment] 2018-08-08 11:44
Hmm, I agree that should work already.  Let me double check and get back to you.  Thanks!

**Comment by nkarasic** [comment] 2018-08-13 20:46
Would this be the reason that the same title & username appear multiple times as entry-list-items, even though they only have one entry in the database?

**Comment by jeffbowman** [comment] 2018-08-21 09:59
In my database, I have one entry for my SSO credentials and then many entries to specific locations with references to the user and password in the SSO entry. So, for example, if I have an entry for Jenkins at my company and I want to use my SSO credentials, then I use the reference to the SSO entry in my Jenkins entry. However, when I actually go to the Jenkins page to login, Tusk will not follow the references to the SSO entry and instead will paste the references themselves (ie: {REF:U@I:....} for the user and {REF:P@I:...} for the password). 

This is marked as needing more details, I'm happy to try to provide more details from my perspective if the above does not provide enough additional information.

Thanks!
Jeff

**Comment by subdavis** [comment] 2018-09-11 01:28
It was a pretty worthless bug - simple case mismatch (upper/lower).  It allowed me to fix some other issues though.  TY.

**Closed** 2018-09-11 01:28 UTC
Labels: bug

**Comment by jeffbowman** [comment] 2018-09-12 17:05
Great news!! I look forward to the update! Thanks for the plugin.

**Comment by kopach** [comment] 2018-12-03 17:44
@subdavis, is solution for this defect was deployed to play store? I do still have this defect reproducible in v2018.9.27

**Comment by subdavis** [comment] 2019-01-03 00:03
It's been fixed and needs to deploy to Chrome Webstore.  Sorry for the delay

**Comment by cdesserich** [comment] 2019-01-04 14:49
> It's been fixed and needs to deploy to Chrome Webstore. Sorry for the delay

No apologies. I was trying to point out that the bug really lies in MacPass, not in Tusk. If Tusk handles it both ways, all the better, but it seems like no delimiters in the UUID seems to be the standard everywhere else besides MacPass. That's all I was saying.

**Comment by kopach** [comment] 2019-01-04 15:22
Thanks @cdesserich for a clarification and your help. I've just removed delimiters manually from UUID and everything works fine for me now.
