### ISSUE TITLE
Unlocking database takes a minute

### ISSUE THREAD

**Issue by pezcode** [subdavis/Tusk#296] opened 2019-02-02 21:00 UTC
### Steps to reproduce

1. Click on the icon
2. Enter password
3. It says "Unlocking database..."
4. Takes one minute to unlock
4.1 High load on 1/4 CPUs, but Firefox UI is completely unresponsive (I can press buttons but nothing happens, including the Tusk icon)

### Expected behaviour

To unlock in a reasonable time frame. KeepassXC takes half a second. I understand web extensions may not be as fast as a C++ desktop program, but this makes it hard to use.

#### Environment 

**OS**: Windows 10 Pro 1809 (October 2018 Update)
**Browser**: Firefox 65.0
Also tested with Chrome 71.0.3578.98, time is still 30+ seconds
**Storage**: Dropbox (kdbx file is 35KB in size)

**Comment by subdavis** [comment] 2019-02-02 21:58
Duplicate of #212

**Closed** 2019-02-02 21:58 UTC
