### ISSUE TITLE
After moving db files to G TeamDrives, can't access files at new location

### ISSUE THREAD

**Issue by ppetershagen** [subdavis/Tusk#270] opened 2018-11-06 03:00 UTC
## Bug report
Hi,

I just moved my 2 keyfile dbs from "My Drive" to 2 different TeamDrive folders. (Tusk 2018.9.27)

Turned off G Drive storage support, deleted cached objects, re-authed, didn't help.

The 2 db files are still connected and displayed in the "Manage Databases" form and the Chrome plugin popup (top right).

### Steps to reproduce - current behaviour

When I choose "Manage Database Files" it takes me to the "Manage Databases" form, but I can't delete the connected db files there and choose new one from the G TeamDrive. 

My workaround currently is, because I need my passwords, to mount the team drive locally and use the file storage approach.

Is that a issue on my side or a bug in Tusk?
How can I reset the file connections and choose new database files in G TeamDrives?

### What is the expected behaviour

I expect to be able to remove the connected database files and point to the new location in the G TeamDrive.

#### Environment 

Linux Mint 19, Chrome Version 70.0.3538.77 (Official Build) (64-bit), Google G Suite Business, separate TeamDrives

**Comment by subdavis** [comment] 2018-11-06 03:16
Have you tried uninstalling and re-installing tusk?

You could also go to advanced settings and clear all your data.

That will erase your past usage data.  If this works, let me know and I can file a bug 

If that doesn't work, this issue is 100% Google's fault and we can weep together.

**Comment by ppetershagen** [comment] 2018-11-06 03:31
Yes, just re-intstalled it, but still not working... the old db files appear again and I don't need to re-auth with drive... Advanced->Stored Data is empty.... 

But how can I reset the settings?

**Comment by ppetershagen** [comment] 2018-11-06 03:36
Ok, I also tried the "Shared Link" and it doesn't add the URL / does nothing... Dev console shows this exception:

14options.build.js:8 Uncaught ReferenceError: getParameterByName is not defined
    at Object.drive.google.com (options.build.js:8)
    at r.processSpecialSources (options.build.js:8)
    at new r (options.build.js:8)
    at addLink (options.build.js:8)
    at e (dll.library.js:118)
    at HTMLAnchorElement.t._withTask.t._withTask (dll.library.js:118)

**Comment by subdavis** [comment] 2018-11-06 03:37
You already reset the settings when you uninstalled it.

This is completely Google's fault.  It looks like it hasn't re-indexed your Drive.

Make sure the files are deleted from the recycle bin or trash or whatever Drive calls it 

Visit myaccount.google.com/permissions and disable Tusk.

Then disable and re-enable Google Drive.  If this doesn't work, you may just have to wait a few days for Google to un-screw it's indexing.

**Comment by subdavis** [comment] 2018-11-06 03:40
Shared links don't work with Tusk, which is why the description doesn't include Google Drive in the list of supported providers.

This is _also_ Google's fault.  As a developer, supporting Google Drive has been a nightmare.

I'm sorry for the trouble, and thanks for opening this issue.  I hope we can figure something out.

**Comment by ppetershagen** [comment] 2018-11-06 03:49
I personally feel it has to do with the separation of the different profiles in Chrome... I use one profile for private and one for business purposes. I just noticed, that the two db files, which pop up, are from my private profile. They shouldn't appear in my business profile at all. 

Unfortunately, removing Tusk from all profiles and closing Chrome, didn't help.

**Comment by subdavis** [comment] 2018-11-26 00:53
@ppetershagen and anyone else still having trouble: see https://github.com/subdavis/Tusk/wiki/Troubleshooting#google-drive-constant-reauthorization

Closing this as duplicate of #133

**Closed by subdavis** 2018-11-26 00:53 UTC
Labels: bug, enhancement, help wanted
