### ISSUE TITLE
Keepass Tusk don't remember masterpassword

### ISSUE THREAD

**Issue by aspergerway** [subdavis/Tusk#327] opened 2019-07-05 15:24 UTC
Whether you set 24 hours or until the browser remains open, the plugin does not remember it, after a short time it requires it.
Also, please enter the possibility to remember it until I close the database. I'll decide when the plugin needs to ask me for the password.

**Comment by subdavis** [comment] 2024-08-08 14:01
Duplicate of #349 (I know this one came first, I'm just consolidating)

**Closed by subdavis** 2024-08-08 14:01 UTC
