### ISSUE TITLE
Hidden inputs breaking autofill on adjacent fields

### ISSUE THREAD

**Issue by fmunch** [subdavis/Tusk#245] opened 2018-09-23 09:36 UTC
### This issue is a

bug

### Steps to reproduce - current behaviour

1. Add an entry to your Keepass database with the URL https://www.creditmutuel.fr/fr/authentification.html
2. Go to https://www.creditmutuel.fr/fr/authentification.html
3. Focus the "Identifiant" (username) field.
4. Hit Ctrl+Shift+Space to autofill username and password.
5. The username is filled but not the password.

### What is the expected behaviour

The autofill should fill both username and password fields.

#### Additional remarks

The problem comes from the hidden inputs sitting between the username and password fields in the form, making them not adjacent.

The `inputPattern` in [inject.js](https://github.com/subdavis/Tusk/blob/develop/background/inject.js#L59) does not seem to be used anymore since 4d856b1, hence the hidden inputs not being filtered.

#### Environment 

**Operating System:** Windows 10 64 bits

**Browser:** Chrome 71.0.3554.4 64 bits

**Storage:** WebDAV (Nextcloud)

**Comment by zmilonas** [comment] 2018-09-23 10:55
Great suggestion. Thank you!

Although we already have an issue for tracking autofill problems, your investigation into specific code snippet causing the issue is greatly appreciated!
I'm gonna close this issue and repost your remarks in that issue.

duplicate of #197

**Closed by zmilonas** 2018-09-23 10:55 UTC
