### ISSUE TITLE
Why are local files not reloaded?

### ISSUE THREAD

**Issue by petersohn** [subdavis/Tusk#265] opened 2018-10-19 18:24 UTC
I use the local file option because I use a file sharing provider that is not among the supported ones. When the database file is modified, it is not moved to Tusk even after a browser restart. Why is that? Why cannot Tusk just reload the file from the disk on startup?

**Comment by subdavis** [comment] 2018-10-19 18:53
It is not possible to have a "reload" button. Browser extensions have no access to the user's filesystem through any interface other than one-time file upload (which Tusk uses).  If you want to easily update the database, please consider using dropbox or google drive.

Chrome does provide https://developer.chrome.com/apps/fileSystem which would technically allow this, but it's not available on other browsers and not standardized by W3C.

**Comment by subdavis** [comment] 2018-10-19 18:55
This may be a duplicate of https://github.com/subdavis/Tusk/issues/88

**Closed by subdavis** 2018-10-19 18:55 UTC
