### ISSUE TITLE
401 when using WebDAV while having a session already open

### ISSUE THREAD

**Issue by fmunch** [subdavis/Tusk#226] opened 2018-09-05 21:06 UTC
### This issue is a

Question, maybe bug.

### Steps to reproduce - current behavior

1. Go to a Nextcloud instance and log in with a regular account.
2. Try add the same instance to Tusk using another account (after working around #210).
3. Results in a 401 response.
4. Log out of Nextcloud (and maybe delete every Nextcloud cookies).
5. Try again to add the database to Tusk.
6. This time it works.
7. If you go back to Nextcloud you are now connected to the account used by Tusk.

Deleting cookies might not be necessary.

### What is the expected behavior

This behavior does not really allow to follow the [best practices](https://github.com/subdavis/Tusk/wiki/WebDAV-Support) since you cannot use your regular account and use Tusk at the same time.

It would be great to isolate Tusk from the rest of the browser activity.

### Environment

**Operating System:** Windows 10 Home 64 bits

**Browser:** Chrome 69.0.3497.81

**Storage:** Nextcloud

**Comment by subdavis** [comment] 2018-09-11 22:11
Answer: Nextcloud bugs(?)

https://github.com/owncloud/core/issues/25927#issuecomment-262703655 seems related.  I'm going to tinker with the setup and see what I can do.  Never sending cookies seems to fix this for nextcloud.

**Comment by subdavis** [comment] 2018-09-11 22:12
Going to call this a duplicate of #210 for now, since I think they all stem from the same issue.

**Closed by subdavis** 2018-09-11 22:12 UTC
