### ISSUE TITLE
Close immediately as if the KeePass window blinked

### ISSUE THREAD

**Issue by saltyshape** [subdavis/Tusk#285] opened 2018-12-27 11:30 UTC
## Bug report
Thank you for developing a wonderful add-on. However, I have one big problem with this add-on. As for how it occurs, when I finish the initial setting of the add-on, clicking the add-on icon will close the small screen of the add-on immediately.
Even if I click on the icon to use KeePass, I can not use it because it closes immediately.

This problem was confirmed that the same OS will occur on two computers with different manufacturers.
### Steps to reproduce - current behaviour
  1. Perform initial setting of Tusk.
  2. Open Tusk from icon.

### What is the expected behaviour
A small screen of the task opens.
 

#### Additional remarks
Similar problems occur on multiple PCs installing the same OS.
 

#### Environment 

**Operating System:**
Ubuntu 18.04.01 LTS 64bit
**Browser vendor and version:**
FireFox 64.0
**Storage Provider:**

**Comment by subdavis** [comment] 2018-12-27 15:21
Duplicate of #146

**Closed** 2018-12-27 15:21 UTC
