### ISSUE TITLE
No matches found for this site.

### ISSUE THREAD

**Issue by ryandoesntstress** [subdavis/Tusk#123] opened 2018-03-09 08:56 UTC
## This issue is a 

- [ ] bug
- [ ] feature
- [x] question

### Please describe the current behavior, and explain why it's bad.

Receiving the message "No matches found for this site." when at hotmail login screen.

### Please describe how you think it should change.

Tusk should automatically bring up my hotmail login credentials

### Anything else?

What am I missing? I made sure the database url matches the login page url and I'm not sure what to try next.

**Comment by subdavis** [comment] 2018-03-21 20:31
I believe I've seen this problem too.  There may be a domain equivalency issue here.

**Comment by Tiger862000** [comment] 2018-06-11 21:45
Hi, I'm actually facing the same issue on Nextcloud. 

**Setup:**
Running a Nextcloud 13 instance on my own home server. 
The URL is from Duckdns.org
KDPX File is synced to my Nextcloud instance

**What I did:**
Sharing my KDPX File through Nextcloud interface as link. No Editing, No Password
Copy that URL into the "Shared Link" section in the Tusk settings and name the database
Enable this Option in the menu
Open the database in the web-addon's dialog
Enter Keepass master password

The result is are described as above: 
It just appears the message "No matches found for this site."
I cannot access this database

The message doen't really describe the error nor suggests improvements to make.
I'm grateful for any idea on how to solve this thing.

Thank you!
Tiger

**Comment by subdavis** [comment] 2018-06-11 21:49
You've said some conflicting things here, so I'd like to clarify:

> No matches found for this site

You can only get this error after unlocking a database, which necessarily implies you have successfully accessed, downloaded, and decrypted it.

> I cannot access this database.

Are you sure?  What happens if you type something like your Hotmail username into the search bar?  Do your other entries appear as you begin to type?  Try entering a single common letter like 'e' or 's'.

I'd like to make sure this is the same issue.

**Comment by zmilonas** [comment] 2018-06-11 21:51
> Sharing my KDPX File through Nextcloud interface as link. No Editing, No Password

Can't find much on the internet about how NextCloud's sharing works but are you sure you have a direct link to a raw file with proper headers? Or is it like a website that has a preview of that file? Can you give us an example link from anywhere?

**Comment by subdavis** [comment] 2018-06-12 00:11
I run a nextcloud server for testing purposes and link sharing works just fine.  It's a direct file link with proper headers.

**Comment by Tiger862000** [comment] 2018-06-12 17:22
Subdavis, you are actually right, the database was unlocked/accessed and decrypted. 
Yet after entering master password no entries appeared and the strange message stays. 
For further ease of explanation please see pics below:
- Pic 1 shows what I get directly after entering password. 
- If I type something entries start to appear, this can be seen in Pic 2 

I can use the tool as intended now. So thank you! Still, the message stays... What does it mean? 

BTW: The Link I entered looks like this: https://subdomain.duckdns.org/index.php/s/cblablablablalink

Pic 1
![screenshot from 2018-06-12 19-08-34](https://user-images.githubusercontent.com/12417480/41305934-c43b5524-6e74-11e8-8948-ce84bd8890a5.png)

Pic 2
![screenshot from 2018-06-12 19-11-49](https://user-images.githubusercontent.com/12417480/41305947-ce67cf5a-6e74-11e8-9c69-99290a38d2f0.png)

**Comment by racquad** [comment] 2018-07-27 18:05
I also have the same problem. I use a local file, it matches for Facebook and Twitter but not for Ali Express, for example. I have tried with several different domains including www, no www and subdomain login but no match was found.

**Comment by subdavis** [comment] 2018-07-27 21:38
@racquad I tried this and it worked for me.

URL should be: "https://login.aliexpress.com", but I also had no problem with "aliexpress.com".  Check your character encoding?  Are there any Latin or Unicode symbols, or are you using a non-US keyboard?  Try copy-pasting the URL from my comment exactly.

**Comment by racquad** [comment] 2018-07-30 08:34
@subdavis I just found out something interesting. I changed my PayPal password and edited it in KeePassXC. When I tried to log in using Tusk I got a wrong password message. I went back to KeePassXC and copied the password directly from there and worked.

So, I went to Tusk configuration, closed the database, removed and put it back again. It worked and now Tusk can see AliExpress.

Useful information:
1) I'm using Firefox 61 on Ubuntu 18.04;
2) I'm using a local file as password repository;
3) I'm using KeePassXC as password manager.

It seems to me that Tusk is somehow caching information and not actually reading it on-the-fly from the repository.

**Comment by zmilonas** [comment] 2018-07-30 08:38
Hi @racquad 
Local File is not recommended since the browser APIs do not allow real-time access to the file system - which is good for security.
As stated in the file upload description: 
> A one-time copy of the file(s) will be saved in your browser's local storage. If you update the database on your local system then you will have to re-upload it in order to see the changes.

So you're right it does cache it, but there is nothing we can do about it.

So was that just a case of not updated database? Can we close the issue?

**Comment by racquad** [comment] 2018-07-30 08:52
@zmilonas I see... So that's the problem I had earlier with Ali Express as well. The entry was added after I uploaded the KDBX to the browser and that was the problem.

Thanks a lot.

**Comment by zmilonas** [comment] 2018-08-03 21:27
Since the original author never provided more details and both @racquad and @Tiger862000 problems seem unrelated to the original issue and were solved I'm going to close it.

**Closed by zmilonas** 2018-08-03 21:27 UTC
Labels: bug, needs more details
