### ISSUE TITLE
Scan is ok / 207, but unlock returns 404?

### ISSUE THREAD

**Issue by pwFoo** [subdavis/Tusk#225] opened 2018-09-03 17:43 UTC
### This issue is a 
bug / question 

Tried to add server "directory", what doesn't work. Added each kdbx file inside of directory what looks good.
There is a redirect ("/" to "/realpath") in webdav as documented here:
https://github.com/keeweb/keeweb/wiki/WebDAV-Config

server side log shows PROPFIND 207 status code during scan.
```
"PROPFIND /file.kdbx/ HTTP/1.1" 207 672
```

If I try to unlock the database I get the redirected path in log and a 404 status code
```
"GET /realpath/file.kdbx HTTP/1.1" 404 9
```

Is it plugin releated? Why scan is fine and unlock not?
Works fine for keeweb.

**Comment by pwFoo** [comment] 2018-09-09 09:07
caddy webserver with webdav plugin. Works fine with keeweb for example.
https://caddyserver.com/docs/http.webdav

**Comment by subdavis** [comment] 2018-09-11 22:05
I can now reproduce this.  Duplicate of #210 

It should be fixed soonish...

**Closed by subdavis** 2018-09-11 22:05 UTC
Labels: bug
