### ISSUE TITLE
Slide to remain logged in until browser exits stopped working

### ISSUE THREAD

**Issue by PalpatineII** [subdavis/Tusk#349] opened 2024-08-06 11:52 UTC
### Steps to reproduce - current behaviour

I cannot really put my finger on it, but it used to be the case that Tusk remained logged in to the vault when you set the slider to 'Until browser exits', this does not seem to work anymore, I have to log in multiple times now, he remembers the session for a short while and then requires a new login.

### What is the expected behaviour
The slider controls the time until next login is required

#### Environment 
OS: Windows 11 Enterprise 23H2,
Browser: Chrome 127.0.6533.89
Storage: Dropbox

**Comment by stromnt** [comment] 2024-08-07 08:31
I am having the same problem. I have been using the Tusk extension for years with no problem. 
I am on mac M1 running macOS 14.4.1 (23E224)
Chrome Version 127.0.6533.89 (Official Build) (arm64)

Unfortunately I cannot revert to the old extension. Every time I navigate away from chrome, I have to reenter my password in Tusk again, regardless of the slider settings.

It appears to be a "idle" timeout - the error appears in google extension.

**Comment by subdavis** [comment] 2024-08-07 13:57
I cannot reproduce this on Chrome Version 127.0.6533.89 (Official Build) (arm64)

> Every time I navigate away from chrome

What does "Navigate away from chrome" mean?

**Comment by Phuturer** [comment] 2024-08-08 16:09
Same issue here. Since the new 2024 changes, the master password entered expires shortly after and has to be re-entered.

I've removed and reinstalled the extension (for some reason my webdav won't connect anymore, 401), but I have tried with the local file. Issue still exists.

I'm using Brave Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64-bit)

**Comment by subdavis** [comment] 2024-08-08 16:23
Just to be clear, I've tried this on 10 browsers across 2 computers / architectures / operating systems.  I cannot reproduce it.  Until someone either gives me a screenshot showing some kind of error, there's nothing I can do here.

I cannot restore the old version of Tusk, google was about to forcefully remove it from the store.

**Comment by RMutton** [comment] 2024-08-08 22:53
I've had this happen multiple times across various instances of Chrome on different Windows machines.
It does not seem to happen when DevTools is open. A few minutes of regular browsing, tabbing to and from chrome and then the database is locked again when set to "Until browser exits" as well as 24 hours.

**Comment by subdavis** [comment] 2024-08-09 04:36
> It does not seem to happen when DevTools is open

That was the hint I needed.  This is caused by the service worker life span.  I'm not sure if there's even a solution to this: there's no place to keep stuff in memory that doesn't get written out to disk.

**Comment by dinhacarina** [comment] 2024-08-09 07:41
Hi @subdavis,
I had the same problem described above: I had to re-enter the KeePass master password every time I wanted to access an account with KeePass over and over again, although the slider to store the master password was activated.

Yesterday, an alert occured in my browser (Firefox), saying: "KeePass Tusk - Password Access and Autofill requires new authorizations." 
I confirmed it, and KeePass Tusk was updated to v2024.8.6. Since then it is working again like it used to before: The master password is stored again.

Maybe this information could be helpful for anyone who is facing the same problem.

Firefox: 129.0
Windows 10 Enterprise 22H2 

![Firefox_KeePass](https://github.com/user-attachments/assets/3b8e3c6d-8e2a-4199-8880-8bbcb340ff95)

**Comment by subdavis** [comment] 2024-08-09 13:59
@dinhacarina it's unlikely that this is the reason most people are having this problem.  The firefox addon works differently than the chrome one, and these people are mostly on chrome.  Firefox briefly upgraded to service worker, but MV3 barely works on firefox, so I downgraded again to MV2.

**Comment by stromnt** [comment] 2024-08-09 18:08
When I probably let chrome become inactive. I switch between Intellij, VS code, Teams, Outlook and Chrome. When I navigate back to Chrome I have to reenter my password. I have tried all levels of the slider, but it makes no difference. Get Outlook for AndroidFrom: Brandon Davis ***@***.***>Sent: Wednesday, August 7, 2024 3:57:57 pmTo: subdavis/Tusk ***@***.***>Cc: Tania Stromnes ***@***.***>; Comment ***@***.***>Subject: Re: [subdavis/Tusk] Slide to remain logged in until browser exits stopped working (Issue #349)
I cannot reproduce this on Chrome Version 127.0.6533.89 (Official Build) (arm64)

Every time I navigate away from chrome

What does "Navigate away from chrome" mean?

**Comment by subdavis** [comment] 2024-08-09 23:45
This will be fixed in 2024.8.10 once it's been through the Chrome store review, probably tomorrow.

**Comment by stromnt** [comment] 2024-08-10 10:59
> This will be fixed in 2024.8.10 once it's been through the Chrome store review, probably tomorrow.

Wow - thank you - I love the tusk extension - really appreciate the support and upgrade. I would hate to have to find an alternative.

**Comment by stromnt** [comment] 2024-08-10 11:14
You are such a star.

Huge thank you Brandon. Judging by the time this went through I assume you must be in US timezone.

I cannot tell you how delighted I am.

Regards
Tania
 


On 10 Aug 2024, at 01:45, Brandon Davis ***@***.***> wrote:


This will be fixed in 2024.8.10 once it's been through the Chrome store review, probably tomorrow.

**Comment by PalpatineII** [comment] 2024-08-10 16:43
Great! Thanks for the very quick response and fix! I kept out of the discussion since there were more then enough people with good input!.

**Closed** 2024-08-13 00:08 UTC
Labels: bug, critical, planned
