### ISSUE TITLE
Google Drive re-auth

### ISSUE THREAD

**Issue by knightr87** [subdavis/Tusk#133] opened 2018-04-02 19:42 UTC
## This issue is a 

- [ ] bug
- [ ] feature
- [x] question

### Please describe the current behavior, and explain why it's bad.

After an unknown amount of time KeePass Tusk requires re-authorization to google drive. I thought once giving access I wouldn't need to again unless revoked. Is there something I need to do in google or is this a bug?

**Comment by subdavis** [comment] 2018-04-02 21:16
This could be a bug, but more likely it's a problem with Google Chrome.

Please read #126 and let me know if that sounds familiar.

**Comment by knightr87** [comment] 2018-04-02 21:28
I am using Firefox. When unlocking the database it says that the auth token has expired and I have to choose an account (I have two). After choosing the correct account everything works as expected (for a few hours at least). I tried manually removing the auth and it still happens.

**Comment by Barondark** [comment] 2018-04-02 21:37
I am having this issue as well. I am using Firefox but I only have one Google account

**Comment by subdavis** [comment] 2018-04-02 23:28
I've never seen this issue on firefox, so it might be easier to find and fix.

What version are you using?  What sort of Google account do you have (regular or GSuite?)

**Comment by theteapirate** [comment] 2018-05-02 14:38
I'm having the same issue. One Google account (G Suite), Firefox 59.0.3, 2FA disabled on Google account. When I close and reopen Firefox, that triggers the need to reauth immediately. Otherwise, after some amount of time (a couple of hours), it'll work as expected, but then needs to reauth. Happy to provide any more info as necessary.

**Comment by subdavis** [comment] 2018-05-07 00:55
Sorry to ghost on this issue.  I'm pretty stumped here, and I can't even think of what to ask you to try.  Google authentication has been a nightmare to support so far.  Needless to say I'm totally unable to reproduce.

Unless you're willing to pop open a debug inspector and check the error logs, I'm grasping at straws.  

For the sake of documentation, when _exactly_ does this happen?

For example:

1. I install Tusk
2. I authorize Google Drive
3. This works for a couple hours; or if I close and reopen Firefox, I need to reauth immediately 100% of the time.

Is this intermittent or reliable to reproduce for you?  Does revoking Tusk access in https://myaccount.google.com/security#connectedapps , reinstalling tusk, and starting over help? 

Sorry for the trouble.

**Comment by knightr87** [comment] 2018-05-08 21:33
I actually just started using the web autotype plugin, so I'll close this.

**Comment by subdavis** [comment] 2018-05-08 22:03
This is still an issue that others have.  It should be left open.

**Comment by tibbsbrookside** [comment] 2018-05-14 17:55
I can confirm that I have this issue on both the following:
Mozilla Firefox 60.0 (64-bit) on Fedora 28
Google Chrome 66.0.3359.170 (64-bit) on Fedora 28

1. Tusk installed and Google Drive enabled.
2. I use the tool to retrieve some credentials.
3. It prompts me for, and I enter, the master password.
4. I can retrieve the credentials.
5. Some time later I use the tool to retrieve some credentials.
6. Sometimes it works.
7. Sometimes it prompts me for, and I enter, the master password again, at which point I have to reauthenticate Google Drive again as it shows as disabled.
8. I reauthenticate Google Drive again.
9. It prompts me for, and I enter, the master password again.
10. I can retrieve the credentials.
11. Back to 5.

I can go through a day, without closing the browser, retrieving various credentials, where sometimes it doesn't ask me to reauthenticate Google Drive at all, and sometimes it asks me to reauthenticate Google Drive pretty much every time.

I haven't tried revoking the access and reinstalling Tusk, but I will do this now and let you know the results.

You will need to talk me through any web browser debugging if that is required.

If you want to me to test anything else, just ask.

**Comment by subdavis** [comment] 2018-05-17 12:50
> I do have both browsers synced to the same account in another machine

That's probably the ticket.  Could you go into more detail about the setup of both machines?

Is Tusk installed on all 4 browsers, and do you use it between all 4?   The auth mechanism is different for chrome and FF - I need to test more thoroughly the sorts of interaction they can have.  

Thanks for being so responsive and thorough with your docs.

**Comment by bonjour81** [comment] 2018-07-25 21:11
Hi there !
I have a similar issue than @tibbsbrookside for a while now.
Tusk on Chrome (at work) works fine, while Tusk on firefox (at home) ask re-auth google drive pretty often.
I use firefox 61.0.1 on ubuntu 16.04.

Since a few weeks I work on re-inforce my private life protection...Could this be due to some cookies settings or any extension ? (like ublock).

**Comment by tibbsbrookside** [comment] 2018-08-03 18:10
Just to confirm that, having disabled the "sync" option in Firefox, the problem persists.

I also use a number of add-ons, including "uBlock Origin".

I will start disabling these add-ons one by one and see if doing so fixes the issue.

I've also amended a number of the "Browser Privacy" settings from the default. If disabling the addons doesn't fix the issue, I will reset these settings back to the default one by one.

**Comment by p-phillips** [comment] 2018-08-06 07:30
I'm having identical problems.  Running Ubuntu 16.04 32 bit  and FF 61.0 (32-bit).

I have Tusk on this machine as well as a laptop at home (also running Ubuntu 16.04 and 64 bit FF), using google drive to store the password file.

It seems to me that the requirement to reauthorise  isn't associated with a browser restart, as my machines are usually up for weeks at a time.   

Happy to try out any possible solutions or run some debugging - just tell me what you need.

Pete

**Comment by tibbsbrookside** [comment] 2018-08-07 10:43
Problem persists on Firefox with "sync" disabled and all addons (except Tusk) disabled.

**Comment by rstacruz** [comment] 2018-08-11 15:47
Having identical problems here on Firefox 61.0.2 on Arch Linux.

**Comment by tibbsbrookside** [comment] 2018-08-15 16:11
Problem persists on a brand new profile in Firefox with everything as the default plus Tusk installed. Not sure what else I can test further.

I no longer seem to experience the same problem on Chrome, and I've not made any configuration changes to the installation since I first reported the problem.

**Comment by subdavis** [comment] 2018-09-11 21:32
This has started happening to me as well on only my work computer - firefox + ubuntu 18.04.  It doesn't happen on my personal laptop - firefox + ubuntu 18.04.

I have 2 profiles with my work profile as the primary.  This is a google apps account - not a regular google gmail account.  

For others on this thread:

* Does this happen with only 1 google profile?
* Does this happen with a normal google account, or google apps?
* Does this happen with a google account you use on multiple devices?

**Comment by zmilonas** [comment] 2018-09-12 08:10
Did we boil it down to Ubuntu by any chance? 
I can't reproduce on macOS, even with two accounts - G Suite and regular. Similar to @subdavis

**Comment by subdavis** [comment] 2018-11-26 01:00
For anyone still struggling here: https://github.com/subdavis/Tusk/wiki/Troubleshooting#google-drive-constant-reauthorization

This is now the official thread for all discussion related to Google Drive authorization issues.  If you are seeing reauth still, but that wiki post doesn't apply to you, please reply to this thread.

**Comment by jaydee864** [comment] 2018-12-18 15:14
@subdavis I'm using Tusk 2018.11.28 with Firefox 64.0 and I'm still seeing the reauthorization issue even though my Google account associated with Google Drive is the top account in the Account Chooser list. I do have Tusk installed on Firefox on two Windows 10 machines, both have the Google accounts in the same order, but I still get the reauthorization prompt even if I have not used my secondary machine in between primary machine sessions.

**Comment by subdavis** [comment] 2018-12-18 22:40
@jaydee864 yeah that's started happening to me too.  I'm losing hope.  Time to try making the request with a specific profile identifier and listening for profile switch changes.

You should really switch to Dropbox.  They seem to care much more about their developer experience.  It's never given me a single problem.

**Comment by joshcangit** [comment] 2019-02-06 04:59
This is still a problem. It will always ask to reauthorize after booting up and then starting Chrome/Chromium.

**Comment by lukengda** [comment] 2019-10-14 17:06
For me it went away after logging out **and** removing the second account. None of the accounts were GSuite accounts, both private. It started exactly on the day i logged in with a second Google account on the browser. The browser is Firefox on Linux.

Another fact: It did not ask me to reauthorize for the first account after logout of the second account. So the authorization was still valid, it looks to me as it could not 'find' the authorization because of the two accounts.

**Comment by subdavis** [comment] 2024-08-17 00:25
I don't think this is an issue anymore, and so much of the chrome / google auth stuff has changed that I'd like to start fresh.

**Closed by subdavis** 2024-08-17 00:25 UTC
Labels: bug, help wanted, spooky
