### ISSUE TITLE
Tusk Firefox Add-On  immediately closes the popup when clicking on the addon icon

### ISSUE THREAD

**Issue by janstuemmel** [subdavis/Tusk#236] opened 2018-09-10 16:01 UTC
### This issue is a bug

BUG

### Steps to reproduce - current behaviour

1. install keepass tusk
2. configure a database file (same behaviour local and cloud)
3. click on the icon, select the configured file
=> tusk immediately closes, and gives following error in debugging console

```
msg.target.ownerGlobal.gBrowser.getTabForBrowser(...) is undefined LoginManagerParent.jsm:134
	receiveMessage resource://gre/modules/LoginManagerParent.jsm:134:25
	receiveMessage jar:file:///usr/lib/firefox/browser/omni.ja!/components/nsBrowserGlue.js:258:15
	receiveMessage self-hosted:1028:17
```

#### Environment 

* Ubuntu 18.04
* Firefox 61.0.1
* storage does not matter: tryed cloud (nextcloud) and local with different algos in kdbx file

**Comment by subdavis** [comment] 2018-09-10 16:36
Duplicate of #146

**Closed by subdavis** 2018-09-10 16:36 UTC
