### ISSUE TITLE
Selecting 'Google Drive' in 'Manage Databases' does not work.

### ISSUE THREAD

**Issue by rahulgarg123** [subdavis/Tusk#293] opened 2019-01-27 19:48 UTC
Enable 'Google Drive' in 'Manage Database' and click 'Allow' when Chrome requests permission. Nothing happens after that with an error saying [Object object] next to Google Drive (See attachment). Dropbox seems to work flawlessly. Dev console does not show any errors.
<img width="962" alt="screen shot 2019-01-27 at 11 43 36 am" src="https://user-images.githubusercontent.com/490804/51806002-51a0b180-2229-11e9-96bd-650bc51218f6.png">
<img width="581" alt="screen shot 2019-01-27 at 11 44 01 am" src="https://user-images.githubusercontent.com/490804/51806005-55343880-2229-11e9-8fc2-3d89ce90fde2.png">

**Comment by dluzak** [comment] 2019-01-30 21:51
I also have similar issue. I am able to give the permissions to Google Drive, but after giving the permissions I can't see any form for choosing the database file.
I use Chromium version 71.0.3578.98 and Tusk version 2018.9.27.

![image](https://user-images.githubusercontent.com/24375045/52014716-943fe380-24e0-11e9-907d-b204d7196bc8.png)

![image](https://user-images.githubusercontent.com/24375045/52014750-a588f000-24e0-11e9-935d-7f00ef540a7e.png)

**Comment by joshcangit** [comment] 2019-02-03 11:59
I also have this problem. It doesn't show a database file even without errors.
Snap version:
```
snap    2.37.1+18.04
snapd   2.37.1+18.04
series  16
ubuntu  18.04
```
Chromium version:
```
Name      Version       Rev  Tracking  Publisher   Notes
chromium  71.0.3578.98  566  stable    canonical*  -
```

**Comment by GrandAlf** [comment] 2019-02-14 20:32
Same here with Brave Browser Version 0.59.34 Chromium: 72.0.3626.81
Tusk version 2018.9.27
It seems like the communication with Google Drive doesn't happen at all, there is no prompt for login

**Comment by kalmanroemer** [comment] 2019-02-22 15:09
I too am having this issue. Would love to give this extension a try, but will have to look elsewhere if it can't interface with Chrome (version: 72.0.3626.109)

**Comment by esdmr** [comment] 2019-03-11 18:10
# (One way of) Steps to reproduce:
0. Make sure you remove the google Auth Token from Tusk first.
1. Disable Chrome Sign-in (Sync) (Also relaunch chrome to apply settings)
2. Try to authenticate in Tusk
## Expected:
App falls back to popup login.
## Unexpected:
App fails to authenticate and instead shows [Object object].
> Unchecked runtime.lastError: The user turned off browser signin

**Comment by DeveloperDan** [comment] 2019-03-23 12:28
Having the same issue. The problem occurs on one laptop and not on others. Could the problem be related to multiple google logins confusing tusk?

**Comment by ikelly** [comment] 2019-03-28 07:40
I started having this problem on my Chromebook after enabling 2-step authentication on my Google account. I disabled 2-step authentication and then signed out of the Chromebook and signed back in, and then Tusk was able to talk to Google Drive again. I then re-enabled 2-step authentication, signed out, and signed back in again, and it continued working. So I'm not sure which of those two steps actually fixed it, but I suspect that my Chromebook had just not been properly signed in since I first enabled 2-step authentication.

**Comment by bhgsbatista** [comment] 2019-04-22 15:15
This is fixed for me on my work PC (I only have one gmail user there). It is likely related to having multiple GUsers logged into the same browser.

**Comment by Aidoboy** [comment] 2019-06-17 14:51
@bhgsbatista In Brave? I'm still getting the issue and I'm only signed in to 1 account.

**Comment by bhgsbatista** [comment] 2019-06-17 15:46
I should note I've switched from Tusk to [KeePassHelper](https://chrome.google.com/webstore/detail/keepasshelper-password-ma/jgnfghanfbjmimbdmnjfofnbcgpkbegj) which uses the KeePassHTTP plugin to fetch passwords from KeePass running on your desktop. This setup works for me since I've always had KeePass open to add / update entries since Tusk didn't have write capacity.

**Comment by subdavis** [comment] 2019-06-17 18:17
I've actually ditched Keepass completely.

What once seemed to me like a cohesive ecosystem of supported apps now feels like a precarious wasteland of half-assed attempts all moving in vaguely different directions.

Tusk was a decent attempt, but the Keepass ecosystem overall is too many things to too many people.  I'd love to drop support for Google, OneDrive, and OwnCloud all together and have it be a dedicated Dropbox read-only helper.

I've switched to Password Store (git + gpg + bash) and I'm much happier now.

Since I no longer use Tusk myself, I think I should either archive it or find someone dedicated to keeping the project alive.

In general KeePassHTTP is a saner and more secure way to get passwords into your browser.

**Comment by Aidoboy** [comment] 2019-06-17 18:26
M'kay, I'll give some of the KeePassHTTP plugins a try, I never really liked in in the past though and I doubt they'll function from Wine on my work Mac.

Thank you for Tusk while it lasted! Made Keepass a whole lot better.

**Comment by joshcangit** [comment] 2019-09-14 15:59
This is no longer a bug but it's still present as a glitch. This does seem related to issue #133. It temporarily goes away after being signed in and having KeePass Tusk been authorized then re-opening the KeePass Tusk settings page.

**Comment by subdavis** [comment] 2024-08-17 00:19
Closing this issue as outdated -- a lot has changed in Google Drive auth.  If this is still coming up, please log again with new details.

**Closed by subdavis** 2024-08-17 00:19 UTC
