### ISSUE TITLE
First argument to DataView constructor must be an ArrayBuffer

### ISSUE THREAD

**Issue by sachabruttin** [subdavis/Tusk#316] opened 2019-05-16 12:28 UTC
## Bug report
I get the messae :  First argument to DataView constructor must be an ArrayBuffer 

### Steps to reproduce - current behaviour
- Connected to a OneDrive database
- I open Tusk
- I input the password
- it doesn't unlock
- Get  "First argument to DataView constructor must be an ArrayBuffer"

### What is the expected behaviour
Database is unlocked

#### Environment 

**Operating System:** Windows 10

**Browser vendor and version:** Google Chrome 74

**Storage Provider:** OneDrive

**Comment by subdavis** [comment] 2019-05-16 12:35
Duplicate of #224

**Closed** 2019-05-16 12:36 UTC
Labels: bug, duplicate
