### ISSUE TITLE
Cache keepass file from cloud

### ISSUE THREAD

**Issue by cool7su** [subdavis/Tusk#222] opened 2018-08-26 09:29 UTC
### This issue is a 

feature

### Steps to reproduce - current behaviour

  1. Disconnect internet
  1. I open Tusk
  1. It doesn't work, needs internet to download keepass db from cloud.

### What is the expected behaviour

 
Tusk can cache downloaded keepass DB from cloud similar as it treat local keepass DB.
Ideally, it shall only update when detects change in Cloud storage. But at least tusk shall be able to use older version when cloud storage/internet not available. e.g. log in to local/intranet site.
#### Environment 

OS:Windows 10
Chrome
Dropbox

**Comment by subdavis** [comment] 2018-08-26 17:05
Duplicate of #220

**Closed by subdavis** 2018-08-26 17:05 UTC
Labels: duplicate
