### ISSUE TITLE
[Firefox][Ubuntu] Tusk randomly closes on click

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [subdavis/Tusk#243] opened 2018-09-22 08:37 UTC
### This issue is a 

bug

### Steps to reproduce - current behaviour

1) I try to open Tusk by clicking on the icon (not from overflow menu)

Tusk opens for 0.5 seconds, I can see "Loading database", then closes.
![tusk-32](https://user-images.githubusercontent.com/21359162/45915289-38db5600-be5b-11e8-8c14-35f4d502adf2.gif)

2) If opened from overflow menu, it sometimes allows to open tusk, but when I click on password entry field, it closes...
![tusk-33](https://user-images.githubusercontent.com/21359162/45915294-590b1500-be5b-11e8-8937-2a6ccc8f50cc.gif)

#### Environment 

**Operating System:**
Ubuntu 18.04

**Browser:**
Firefox 62.0 (64-bit)

**Storage:** dropbox (not relevant?)

**Comment by subdavis** [comment] 2018-09-22 12:30
Duplicate of #146.  This is a browser bug that Firefox needs to fix.  See workarounds at the bottom of that issue.

There have been like 5 duplicates of this issue.  Please search the issue tracker before you go to all the trouble of creating a new ticket.

Thanks for the report

**Closed** 2018-09-22 12:30 UTC
