### ISSUE TITLE
allways 'Network Error' using nextcloud share link to database

### ISSUE THREAD

**Issue by aeytom** [subdavis/Tusk#216] opened 2018-08-09 16:32 UTC
## This issue is a 

- [ x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

using nextcloud share link to database gives 'network error' while unlocking the database. Same database as local copy works. System is a acer chromebook tab 10.

```
sharedUrlList:Array[1]
  0:Object
    direct_link:"https://cloud.xxxxx.de/s/xxxxxx/download"
    origin:"cloud.xxxxx.de"
    title:"private"
    url:"https://cloud.xxxxx.de/s/xxxxx"
```

**Comment by subdavis** [comment] 2018-08-09 16:40
Possible duplicate of #210

**Closed** 2018-08-11 21:17 UTC
Labels: duplicate
